/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author 91805
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftMenu = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        lbl4 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        lbl5 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        lbl6 = new javax.swing.JLabel();
        rightWorkArea = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jp4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftMenu.setBackground(new java.awt.Color(255, 204, 204));
        leftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setBackground(new java.awt.Color(255, 204, 204));
        tab1.setForeground(new java.awt.Color(255, 255, 255));
        tab1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Dashboard");
        lbl1.setAlignmentX(0.5F);
        lbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });
        tab1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 50));

        leftMenu.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 310, 60));

        tab2.setBackground(new java.awt.Color(255, 204, 204));
        tab2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("K to 12");
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });
        tab2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 105, 40));

        leftMenu.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 60));

        tab3.setBackground(new java.awt.Color(255, 204, 204));
        tab3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Graduate");
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });
        tab3.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 135, 60));

        leftMenu.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 70));

        tab4.setBackground(new java.awt.Color(255, 204, 204));

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("Collect details");
        lbl4.setToolTipText("");
        lbl4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tab4.add(lbl4);

        leftMenu.add(tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 310, 60));

        tab5.setBackground(new java.awt.Color(255, 204, 204));
        tab5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbl5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl5.setText("K to 12");
        lbl5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5MouseClicked(evt);
            }
        });
        tab5.add(lbl5);

        leftMenu.add(tab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 190, 50));

        tab6.setBackground(new java.awt.Color(255, 204, 204));

        lbl6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl6.setText("Graduate");
        lbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl6MouseClicked(evt);
            }
        });
        tab6.add(lbl6);

        leftMenu.add(tab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 60));

        getContentPane().add(leftMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 710));

        rightWorkArea.setBackground(new java.awt.Color(255, 204, 204));
        rightWorkArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp1.setBackground(new java.awt.Color(153, 255, 255));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        rightWorkArea.add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 700));

        jp2.setBackground(new java.awt.Color(153, 255, 255));
        jp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        jp2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        rightWorkArea.add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 650, 700));

        jp3.setBackground(new java.awt.Color(153, 255, 255));
        jp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Student Details");
        jp3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 190, 40));

        jLabel10.setText("Name");
        jp3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, -1));
        jp3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 230, -1));

        jCheckBox1.setText("Science");
        jp3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jCheckBox2.setText("Maths");
        jp3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jCheckBox3.setText("Language");
        jp3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jCheckBox4.setText("jCheckBox4");
        jp3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jCheckBox5.setText("jCheckBox5");
        jp3.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jCheckBox6.setText("jCheckBox6");
        jp3.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel11.setText("Have you completed 10th");
        jp3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jRadioButton3.setText("Yes");
        jp3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jRadioButton4.setText("No");
        jp3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel12.setText("Select subjects taught");
        jp3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel13.setText("Average % of past 3 years");
        jp3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jp3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 270, -1));

        jLabel14.setText("Current %");
        jp3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));
        jp3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 270, -1));

        jButton2.setText("Save");
        jp3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        rightWorkArea.add(jp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 650, 700));

        jp4.setBackground(new java.awt.Color(153, 255, 255));
        jp4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Name");
        jp4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 60, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jp4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 330, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jp4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 330, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jp4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 330, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Position");
        jp4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Company working");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jp4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jp4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 330, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Employment History");
        jp4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 190, 30));

        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jp4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        jRadioButton2.setText("No");
        jp4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Were you demoted?");
        jp4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jButton1.setText("Save");
        jp4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Employee details");
        jp4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 210, 30));

        rightWorkArea.add(jp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 650, 700));

        getContentPane().add(rightWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 660, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        // TODO add your handling code here:
        //tab2.setVisible(true);
        //tab3.setVisible(true);
    }//GEN-LAST:event_lbl1MouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
    }//GEN-LAST:event_lbl2MouseClicked

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        // TODO add your handling code here:
         jp1.setVisible(false);
        jp2.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);
    }//GEN-LAST:event_lbl3MouseClicked

    private void lbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(true);
        jp4.setVisible(false);
    }//GEN-LAST:event_lbl5MouseClicked

    private void lbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl6MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(true);
    }//GEN-LAST:event_lbl6MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JPanel leftMenu;
    private javax.swing.JPanel rightWorkArea;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    // End of variables declaration//GEN-END:variables
}
